fix path when putting bin folder back
huan/docker-windows pull request #3
Opened 2021-10-08 07:20 UTC by hcfw007

when you move /bin to /bin.bak, you will lost access to most commands like tar, mv, etc.

corresponding issue: https://github.com/huan/docker-windows/issues/2

2021-10-10 07:01 UTC, huan requested changes
Thank you very much for noticing this problem!

Please:

1. Change the docker image to as the following, [which is based on Debian distribution](https://github.com/huan/docker-wine/blob/main/Dockerfile#L1):
    ```diff
    - FROM zixia/wine:5.0
    + FROM zixia/wine:6.0
    ```
2. Follow the [installation guide](https://github.com/just-containers/s6-overlay#installation) with the Debian command:
    ```sh
    RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
    ```
3. Please bump the minor version of [VERSION](https://github.com/huan/docker-windows/blob/master/VERSION) file.

After that, I believe this PR will be fit our needs for the next version.

2021-10-14 03:18 UTC, huan commented on VERSION
> +0.2.3
Please bumping the minor version instead of the patch version because this change need to be published as a new docked image version.

Change version to: 0.3.0

2021-10-14 03:27 UTC, hcfw007 commented on VERSION
> +0.2.3
OK

2021-10-14 10:06 UTC, huan approved these changes
LGTM

I hope this will fix #1 

Thank you very much for the contribution!

2021-10-14 10:07 UTC, merged